services:
  server:
    image: registry.jetbrains.team/p/tasktracker-3/sharable/tasktracker-server:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/tasktracker
      - DB_USERNAME=mikrise2
      - DB_PASSWORD=Mikmikmik25522552