pluginName: Refactoring course
pluginDescription: "We want to track your progress through the kotlin introduction course in order to collect data on file changes during the course completion. Please, when you are ready, press the next button."
researchId: "Kotlin Introduction"
logs:
  - logPaths:
      - "eduAssistant.log"
    type: "ai"