pluginName: "AI Debugger Study"
pluginDescription: "We want to track your progress through the course in order to collect data on file changes during the course completion. Please, when you are ready, press the next button."
researchId: "DEBUGGER"

logs:
  - logPaths:
      - "ai-debugging/aiDebugging.log"
    type: "assistant"
    isInPluginDirectory: true
