pluginName: "Kotlin Refactoring course"
pluginDescription: "We want to track your progress through the kotlin refactoring course in order to collect data on file changes during the course completion. Please, when you are ready, press the next button."
researchId: "Kotlin Refactoring"
logs:
  - logPaths:
      - "edu-assistant/eduAssistant.log"
    type: "assistant"
    isInPluginDirectory: true