scenario:
  steps:
    - units:
        - !<Task>
          id: "hello"
        - !<Survey>
          id: "default"
      mode: SHUFFLED
      ideConfig:
        settingsConfig:
          theme: LIGHT
        inspectionConfig:
          mode: DISABLE_SELECTED
          inspectionNames:
            - "EmptyFinallyBlock"
    - units:
        - !<Setting>
          mainIdeConfig:
            settingsConfig:
              enableCodeCompletion: OFF
        - !<List>
          taskIds:
            - "hello"
            - "example"
    - units:
        - !<SingleList>
          taskIds:
            - "hello"
            - "example"
            - "style"
        - !<External>
          url: "https://github.com/JetBrains-Research/tasktracker-3"