defaultMessageTemplate: "  No worries, though! You can still send us your tracked data manually. Here's what to do:
            
            Copy this link: <i>%s</i>
            Open the folder using the link.
            Once you're in the folder, please send us all its files.
            
            We appreciate your assistance!"