surveys:
  - id: general
    htmlQuestions:
      - !<Input>
        text: What is your age?
        elementId: age
        required: true
      - !<Input>
        text: What university do you study at?
        elementId: university
        required: true
      - !<Radio>
        text: What year of Bachelor study are you in now?
        elementId: studyYear
        required: true
        info:
          - id: studyYear1
            value: First
          - id: studyYear2
            value: Second
          - id: studyYear3
            value: Third
      - !<Radio>
        text: I have no prior experience with Kotlin
        elementId: experience
        required: true
        info:
          - id: experienceYes
            value: Yes
          - id: experienceNo
            value: No
      - !<Textarea>
        text: Briefly describe your previous programming experience - what languages do you know and at what level?
        elementId: experienceDescribe
        required: true
        rows: 5
        cols: 50
      - !<Radio>
        text: I am ready to participate in a follow-up interview
        elementId: readyToParticipate
        info:
          - id: readyToParticipateYes
            value: Yes
  - id: final
    htmlQuestions:
      - !<Textarea>
        text: Briefly describe the situations in which you needed help from the AI-generated hints
        elementId: needHints
        required: true
        rows: 5
        cols: 50
      - !<Textarea>
        text: Please share with us up to 3 examples when hints did not help you to get unstuck
        elementId: notHelp
        required: true
        rows: 5
        cols: 50
      - !<Textarea>
        text: If the hint didn't work for you, what helped you to solve the task?
        elementId: whatHelped
        rows: 5
        cols: 50
      - !<Textarea>
        text: What aspects (clarity, level of detail, or something else) of the AI hints did you find most helpful for your learning?
        elementId: aspects
        rows: 5
        cols: 50
      - !<Textarea>
        text: If you have any comments about the system you used, please leave them here
        elementId: comments
        rows: 5
        cols: 50
