tasks:
  - description: "Take the kotlin introduction course, and after that, press the next button."
    files:
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: TheFirstDateWithProgramming/task/src/main/kotlin/jetbrains/kotlin/course/first/date
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: WarmUp/task/src/main/kotlin/jetbrains/kotlin/course/warmup
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: LastPush/task/src/main/kotlin/jetbrains/kotlin/course/last/push
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: MastermindAdvanced/task/src/main/kotlin/jetbrains/kotlin/course/mastermind/advanced
        sourceSet: SRC
      - extension: KOTLIN
        filename: RealQuestions
        isInternal: false
        relativePath: TheFirstDateWithProgramming/task/src/main/kotlin/jetbrains/kotlin/course/first/date
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: AlmostDone/task/src/main/kotlin/jetbrains/kotlin/course/almost/done
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Hangman/task/src/main/kotlin/jetbrains/kotlin/course/hangman
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: FeedbackSurvey/Survey/src
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Introduction/task/src/main/kotlin/jetbrains/kotlin/course/welcome
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Chat/task/src/main/kotlin/jetbrains/kotlin/course/chat
        sourceSet: SRC
      - extension: KOTLIN
        filename: Util
        isInternal: false
        relativePath: WarmUp/task/src/main/kotlin/jetbrains/kotlin/course/warmup
        sourceSet: SRC
    id: main
    name: "Kotlin Introduction"