tasks:
  - description: >
      Please follow the instructions in the manual, and when you have completed the course, return to this tab and click “next.” After a few seconds, a survey will appear.
    files:
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Introduction/task/src/main/kotlin/jetbrains/kotlin/course/welcome
        sourceSet: SRC
      - extension: KOTLIN
        filename: RealQuestions
        isInternal: false
        relativePath: TheFirstDateWithProgramming/task/src/main/kotlin/jetbrains/kotlin/course/first/date
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: TheFirstDateWithProgramming/task/src/main/kotlin/jetbrains/kotlin/course/first/date
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Hangman/CompleteTheProject/src/main/kotlin/jetbrains/kotlin/course/hangman
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Hangman/CreateTheGame/src/main/kotlin/jetbrains/kotlin/course/hangman
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: AlmostDone/task/src/main/kotlin/jetbrains/kotlin/course/almost/done
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: LastPush/CompleteTheProject/src/main/kotlin/jetbrains/kotlin/course/last/push
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: LastPush/PatternsGenerator/src/main/kotlin/jetbrains/kotlin/course/last/push
        sourceSet: SRC
    id: main
    name: "Solve Kotlin Onboarding Introduction course"