tasks:
  - description: >
      Solve "Introduction" and "The first date with programming" lessons, and then press "Next".
    id: introductory_tasks
    files:
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Introduction/task/src/main/kotlin/jetbrains/kotlin/course/welcome
        sourceSet: SRC
      - extension: KOTLIN
        filename: RealQuestions
        isInternal: false
        relativePath: TheFirstDateWithProgramming/task/src/main/kotlin/jetbrains/kotlin/course/first/date
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: TheFirstDateWithProgramming/task/src/main/kotlin/jetbrains/kotlin/course/first/date
        sourceSet: SRC
    name: "Introduction"
  - description: >
      Please open the first "Hangman" task and read its description. You have 3 minutes for this.
    files:
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Hangman/CompleteTheProject/src/main/kotlin/jetbrains/kotlin/course/hangman
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Hangman/CreateTheGame/src/main/kotlin/jetbrains/kotlin/course/hangman
        sourceSet: SRC
    id: pre_test_intro
    name: "Hangman First part"
  - description: >
      Please open the next "Hangman" task and read its description, you will need to debug and fix the code. You have 7 minutes for this.
    files:
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Hangman/CompleteTheProject/src/main/kotlin/jetbrains/kotlin/course/hangman
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: Hangman/CreateTheGame/src/main/kotlin/jetbrains/kotlin/course/hangman
        sourceSet: SRC
    id: pre_test_main
    name: "Hangman Second part"
  - description: >
      Please spend the next 40 minutes working on the “Almost Done” lesson. 
      During this time, the AI Debugger will be available—when you press “Check” and your solution doesn’t pass, it will appear to offer guidance. 
      If you run into any bugs or errors, use the feature to help identify and fix the issue.
      Don't worry if you're unable to finish the lesson in 40 minutes; focus on learning and making progress.
    files:
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: AlmostDone/task/src/main/kotlin/jetbrains/kotlin/course/almost/done
        sourceSet: SRC
    id: ai_assistant_training
    name: "Almost done Task"
  - description: >
      Please open the first "Last push" task and read its description. You have 3 minutes for this.
    files:
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: LastPush/CompleteTheProject/src/main/kotlin/jetbrains/kotlin/course/last/push
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: LastPush/PatternsGenerator/src/main/kotlin/jetbrains/kotlin/course/last/push
        sourceSet: SRC
    id: post_test_intro
    name: "Last Push First part"
  - description: >
      Please open the next "Last push" task and read its description, you will need to debug and fix the code. You have 7 minutes for this.
    files:
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: LastPush/CompleteTheProject/src/main/kotlin/jetbrains/kotlin/course/last/push
        sourceSet: SRC
      - extension: KOTLIN
        filename: Main
        isInternal: false
        relativePath: LastPush/PatternsGenerator/src/main/kotlin/jetbrains/kotlin/course/last/push
        sourceSet: SRC
    id: post_test_main
    name: "Last Push Second part"