emotions:
  - modelPosition: -1
    name: "DEFAULT"

  - modelPosition: 0
    name: "NEUTRAL"

  - modelPosition: 1
    name: "HAPPINESS"

  - modelPosition: 2
    name: "SURPRISE"

  - modelPosition: 3
    name: "SADNESS"

  - modelPosition: 4
    name: "ANGER"

  - modelPosition: 5
    name: "DISGUST"

  - modelPosition: 6
    name: "FEAR"

  - modelPosition: 7
    name: "CONTEMPT"
