text: "Feel free to work in your development environment for as long as you'd like, and we'll continue monitoring your emotions. 

After one hour, you'll receive a pop-up inviting you to take a feedback survey. However, if you'd like to provide feedback earlier, you can do so by clicking on the \"Next\" button.

<i>Please note that we only receive the data from your participation when you submit the survey.</i>"